apiVersion: apps/v1
kind: Deployment
metadata:
  name: rpc-server-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rpc-server
  template:
    metadata:
      labels:
        app: rpc-server
    spec:
      containers:
        - name: rpc-server
          image: localhost:5000/rpc-server-image
          ports:
            - containerPort: 8888
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: rpc-server-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: rpc-server-deployment
  minReplicas: 1
  maxReplicas: 7
  targetCPUUtilizationPercentage: 80
